apiVersion: v1
kind: LLMAPIRequester
metadata:
  name: azure-tts
  label:
    en_US: Azure Speech
    zh_Hans: Azure 语音
  icon: azure.svg
spec:
  config:
  - name: base_url
    label:
      en_US: Base URL
      zh_Hans: 基础 URL
    type: string
    required: true
    default: https://eastus.tts.speech.microsoft.com
  - name: timeout
    label:
      en_US: Timeout
      zh_Hans: 超时时间
    type: integer
    required: true
    default: 120
  support_type:
  - llm
  provider_category: manufacturer
execution:
  python:
    path: ./catalog_requester.py
    attr: AzureTTSRequester
